import type { Category, Product } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Fruits', slug: 'fruits', image: 'https://placehold.co/300x300', data_ai_hint: 'organic fruits basket' },
  { id: '2', name: 'Vegetables', slug: 'vegetables', image: 'https://placehold.co/300x300', data_ai_hint: 'fresh vegetables market' },
  { id: '3', name: 'Dairy', slug: 'dairy', image: 'https://placehold.co/300x300', data_ai_hint: 'dairy products on table' },
  { id: '4', name: 'Grocery', slug: 'grocery', image: 'https://placehold.co/300x300', data_ai_hint: 'daily essentials kitchen' },
];

const tomorrow = new Date();
tomorrow.setDate(tomorrow.getDate() + 1);
tomorrow.setHours(23, 59, 59, 999);

const inSixHours = new Date();
inSixHours.setHours(inSixHours.getHours() + 6);

export const products: Product[] = [
  // Fruits
  { id: 'p1', name: 'Kele (Banana)', price: 35, originalPrice: 45, unit: '/dozen', description: 'Fresh and nutritious bananas.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 150, rating: 4.7, data_ai_hint: 'bunch of bananas realistic white background', dealEndTime: inSixHours.toISOString(), badges: ['Deal of the Day', 'Fresh Pick'] },
  { id: 'p2', name: 'Aam (Mango)', price: 80, unit: '/kg', description: 'Sweet and juicy seasonal mangoes.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Seasonal Fruits', stock: 100, rating: 4.9, data_ai_hint: 'ripe mangoes realistic wooden background' },
  { id: 'p3', name: 'Seb (Apple)', price: 100, originalPrice: 120, unit: '/kg', description: 'Crisp and delicious red apples.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 100, rating: 4.6, data_ai_hint: 'red apples realistic white background', badges: ['Hot Deal'] },
  { id: 'p4', name: 'Tarbooj (Watermelon)', price: 30, unit: '/kg', description: 'Refreshing and hydrating watermelon.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Seasonal Fruits', stock: 50, rating: 4.8, data_ai_hint: 'watermelon slice top angle' },
  { id: 'p5', name: 'Santra (Orange)', price: 60, unit: '/kg', description: 'Tangy and vitamin C rich oranges.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 80, rating: 4.5, data_ai_hint: 'oranges close up' },
  { id: 'p6', name: 'Papita (Papaya)', price: 40, unit: '/kg', description: 'Sweet and healthy papayas.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 70, rating: 4.6, data_ai_hint: 'papaya cut open' },
  { id: 'p7', name: 'Amrood (Guava)', price: 50, unit: '/kg', description: 'Sweet and fragrant guavas.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 60, rating: 4.7, data_ai_hint: 'guava white background' },
  { id: 'p8', name: 'Angoor (Grapes)', price: 70, unit: '/kg', description: 'Bunches of sweet green grapes.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 90, rating: 4.8, data_ai_hint: 'green grapes bunch' },
  { id: 'p9', name: 'Anar (Pomegranate)', price: 150, unit: '/kg', description: 'Juicy and antioxidant-rich pomegranates.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Exotic Fruits', stock: 40, rating: 4.9, data_ai_hint: 'pomegranate seeds close up' },
  { id: 'p10', name: 'Nimbu (Lemon)', price: 5, unit: '/piece', description: 'Fresh and tangy lemons.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 200, rating: 4.4, data_ai_hint: 'lemons wooden background' },
  { id: 'p11', name: 'Nariyal (Coconut)', price: 30, unit: '/piece', description: 'Fresh tender coconut.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 100, rating: 4.7, data_ai_hint: 'coconut with straw' },
  { id: 'p12', name: 'Chikoo (Sapodilla)', price: 60, unit: '/kg', description: 'Sweet and grainy chikoo.', image: 'https://placehold.co/600x600', category: 'fruits', subCategory: 'Popular Fruits', stock: 50, rating: 4.5, data_ai_hint: 'chikoo fruit' },

  // Vegetables
  { id: 'v1', name: 'Aloo (Potato)', price: 25, originalPrice: 30, unit: '/kg', description: 'Versatile and essential potatoes.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Root Vegetables', stock: 300, rating: 4.5, data_ai_hint: 'potatoes in basket', dealEndTime: tomorrow.toISOString(), badges: ['Best Value'] },
  { id: 'v2', name: 'Tamatar (Tomato)', price: 40, unit: '/kg', description: 'Juicy and ripe red tomatoes.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Leafy Greens', stock: 250, rating: 4.6, data_ai_hint: 'tomatoes on vine' },
  { id: 'v3', name: 'Pyaaz (Onion)', price: 20, originalPrice: 35, unit: '/kg', description: 'Essential for every Indian kitchen.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Root Vegetables', stock: 400, rating: 4.4, data_ai_hint: 'onions white background', badges: ['Hot Deal', 'Limited Stock'] },
  { id: 'v4', name: 'Baingan (Brinjal)', price: 40, unit: '/kg', description: 'Fresh and glossy brinjals.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Gourds', stock: 100, rating: 4.3, data_ai_hint: 'brinjal eggplant top angle' },
  { id: 'v5', name: 'Bhindi (Okra)', price: 50, unit: '/kg', description: 'Tender and fresh ladyfingers.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Leafy Greens', stock: 120, rating: 4.7, data_ai_hint: 'okra ladyfinger close up' },
  { id: 'v6', name: 'Phool Gobi (Cauliflower)', price: 30, unit: '/piece', description: 'A fresh head of cauliflower.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Cruciferous', stock: 80, rating: 4.5, data_ai_hint: 'cauliflower head white background' },
  { id: 'v7', name: 'Patta Gobi (Cabbage)', price: 25, unit: '/piece', description: 'A fresh head of cabbage.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Cruciferous', stock: 90, rating: 4.4, data_ai_hint: 'cabbage close up' },
  { id: 'v8', name: 'Lauki (Bottle Gourd)', price: 30, unit: '/kg', description: 'Fresh and tender bottle gourd.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Gourds', stock: 70, rating: 4.6, data_ai_hint: 'bottle gourd wooden background' },
  { id: 'v9', name: 'Karela (Bitter Gourd)', price: 50, unit: '/kg', description: 'Fresh bitter gourd.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Gourds', stock: 60, rating: 4.2, data_ai_hint: 'bitter gourd close up' },
  { id: 'v10', name: 'Kaddu (Pumpkin)', price: 25, unit: '/kg', description: 'Sweet and fleshy pumpkin.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Gourds', stock: 50, rating: 4.5, data_ai_hint: 'pumpkin slice' },
  { id: 'v11', name: 'Matar (Green Peas)', price: 60, unit: '/kg', description: 'Sweet and tender green peas.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Leafy Greens', stock: 150, rating: 4.7, data_ai_hint: 'green peas in pod' },
  { id: 'v12', name: 'Lehsun (Garlic)', price: 120, unit: '/kg', description: 'Aromatic and flavorful garlic.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Root Vegetables', stock: 200, rating: 4.8, data_ai_hint: 'garlic bulb white background' },
  { id: 'v13', name: 'Adrak (Ginger)', price: 100, unit: '/kg', description: 'Fresh and pungent ginger.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Root Vegetables', stock: 180, rating: 4.7, data_ai_hint: 'ginger root wooden table' },
  { id: 'v14', name: 'Hari Mirch (Green Chilli)', price: 10, unit: '/100g', description: 'Spicy green chillies.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Leafy Greens', stock: 300, rating: 4.6, data_ai_hint: 'green chillies close up' },
  { id: 'v15', name: 'Kheera (Cucumber)', price: 30, unit: '/kg', description: 'Cool and crisp cucumbers.', image: 'https://placehold.co/600x600', category: 'vegetables', subCategory: 'Gourds', stock: 150, rating: 4.5, data_ai_hint: 'cucumbers sliced white background' },

  // Dairy
  { id: 'd1', name: 'Doodh (Milk)', price: 52, originalPrice: 58, unit: '/litre', description: 'Fresh and pure cow milk.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 100, rating: 4.8, data_ai_hint: 'milk bottle clean background', dealEndTime: tomorrow.toISOString(), badges: ['Best Value'] },
  { id: 'd2', name: 'Dahi (Curd)', price: 30, unit: '/500g', description: 'Thick and creamy curd.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 80, rating: 4.7, data_ai_hint: 'curd in clay pot' },
  { id: 'd3', name: 'Paneer', price: 90, originalPrice: 100, unit: '/200g', description: 'Fresh and soft cottage cheese.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 60, rating: 4.9, data_ai_hint: 'paneer cubes white background', badges: ['Hot Deal'] },
  { id: 'd4', name: 'Makhan (Butter)', price: 50, unit: '/100g', description: 'Creamy and delicious butter.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 70, rating: 4.8, data_ai_hint: 'butter stick on plate' },
  { id: 'd5', name: 'Ghee', price: 250, unit: '/500g', description: 'Pure and aromatic desi ghee.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 50, rating: 4.9, data_ai_hint: 'ghee in glass jar' },
  { id: 'd6', name: 'Cheese Slices', price: 70, unit: '/100g', description: 'Pack of processed cheese slices.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Cheese', stock: 40, rating: 4.6, data_ai_hint: 'cheese slices stacked' },
  { id: 'd7', name: 'Flavoured Milk', price: 25, unit: '/bottle', description: 'Badam flavored milk.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Beverages', stock: 90, rating: 4.5, data_ai_hint: 'flavored milk bottle' },
  { id: 'd8', name: 'Lassi', price: 40, unit: '/glass', description: 'Sweet and refreshing Punjabi lassi.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Beverages', stock: 100, rating: 4.7, data_ai_hint: 'lassi in traditional glass' },
  { id: 'd9', name: 'Chaas (Buttermilk)', price: 20, unit: '/500ml', description: 'Spiced buttermilk.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Beverages', stock: 120, rating: 4.6, data_ai_hint: 'buttermilk in glass' },
  { id: 'd10', name: 'Fresh Cream', price: 60, unit: '/200ml', description: 'Fresh dairy cream.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 50, rating: 4.7, data_ai_hint: 'cream in a bowl' },
  { id: 'd11', name: 'Khoya (Mawa)', price: 120, unit: '/250g', description: 'Evaporated milk solids for sweets.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 30, rating: 4.8, data_ai_hint: 'khoya mawa white background' },
  { id: 'd12', name: 'Toned Milk', price: 45, unit: '/litre', description: 'Low-fat toned milk.', image: 'https://placehold.co/600x600', category: 'dairy', subCategory: 'Milk Products', stock: 100, rating: 4.6, data_ai_hint: 'milk packet carton' },

  // Grocery
  { id: 'g1', name: 'Basmati Chawal (Rice)', price: 120, unit: '/kg', description: 'Long-grain and aromatic Basmati rice.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 200, rating: 4.8, data_ai_hint: 'basmati rice in bowl' },
  { id: 'g2', name: 'Sona Masoori Chawal (Rice)', price: 80, unit: '/kg', description: 'Medium-grain Sona Masoori rice.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 250, rating: 4.7, data_ai_hint: 'sona masoori rice sack' },
  { id: 'g3', name: 'Atta (Wheat Flour)', price: 38, originalPrice: 42, unit: '/kg', description: 'Whole wheat flour for chapatis.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 300, rating: 4.6, data_ai_hint: 'atta wheat flour sack', badges: ['Best Value'] },
  { id: 'g4', name: 'Sarson Tel (Mustard Oil)', price: 150, unit: '/litre', description: 'Pure and pungent mustard oil.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Oils', stock: 100, rating: 4.7, data_ai_hint: 'mustard oil bottle' },
  { id: 'g5', name: 'Refined Oil', price: 130, unit: '/litre', description: 'Refined sunflower oil for cooking.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Oils', stock: 150, rating: 4.5, data_ai_hint: 'sunflower oil bottle' },
  { id: 'g6', name: 'Cheeni (Sugar)', price: 45, unit: '/kg', description: 'Refined white sugar.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 400, rating: 4.4, data_ai_hint: 'sugar cubes stacked' },
  { id: 'g7', name: 'Namak (Salt)', price: 20, unit: '/kg', description: 'Iodized table salt.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 500, rating: 4.5, data_ai_hint: 'salt shaker white background' },
  { id: 'g8', name: 'Toor Dal (Arhar)', price: 110, unit: '/kg', description: 'Split pigeon peas.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Lentils', stock: 180, rating: 4.7, data_ai_hint: 'toor dal in bowl' },
  { id: 'g9', name: 'Chana Dal', price: 90, unit: '/kg', description: 'Split Bengal gram.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Lentils', stock: 160, rating: 4.6, data_ai_hint: 'chana dal in bowl' },
  { id: 'g10', name: 'Moong Dal', price: 120, unit: '/kg', description: 'Split green gram.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Lentils', stock: 150, rating: 4.8, data_ai_hint: 'moong dal in bowl' },
  { id: 'g11', name: 'Masoor Dal', price: 100, unit: '/kg', description: 'Red lentils.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Lentils', stock: 170, rating: 4.6, data_ai_hint: 'masoor dal in bowl' },
  { id: 'g12', name: 'Haldi Powder (Turmeric)', price: 20, unit: '/100g', description: 'Pure turmeric powder.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Spices', stock: 300, rating: 4.7, data_ai_hint: 'turmeric powder heap' },
  { id: 'g13', name: 'Lal Mirch Powder (Chilli)', price: 25, unit: '/100g', description: 'Spicy red chilli powder.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Spices', stock: 280, rating: 4.5, data_ai_hint: 'chilli powder heap' },
  { id: 'g14', name: 'Jeera (Cumin Seeds)', price: 30, unit: '/100g', description: 'Aromatic cumin seeds.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Spices', stock: 250, rating: 4.8, data_ai_hint: 'cumin seeds close up' },
  { id: 'g15', name: 'Dhania Powder (Coriander)', price: 22, unit: '/100g', description: 'Fragrant coriander powder.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Spices', stock: 270, rating: 4.6, data_ai_hint: 'coriander powder heap' },
  { id: 'g16', name: 'Parle-G Biscuits', price: 10, unit: '/pack', description: 'Classic Parle-G biscuits.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Snacks', stock: 500, rating: 4.9, data_ai_hint: 'parle-g biscuit packet' },
  { id: 'g17', name: 'Bhujia Namkeen', price: 35, originalPrice: 40, unit: '/200g', description: 'Spicy and crispy bhujia.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Snacks', stock: 200, rating: 4.7, data_ai_hint: 'bhujia namkeen realistic bowl', dealEndTime: inSixHours.toISOString() },
  { id: 'g18', name: 'Tata Tea Gold', price: 150, unit: '/250g', description: 'Rich and aromatic tea leaves.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Beverages', stock: 100, rating: 4.8, data_ai_hint: 'tea packet realistic' },
  { id: 'g19', name: 'Nescafe Coffee', price: 100, unit: '/50g', description: 'Instant coffee powder.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Beverages', stock: 120, rating: 4.7, data_ai_hint: 'nescafe coffee jar' },
  { id: 'g20', name: 'Maggi Noodles', price: 10, originalPrice: 12, unit: '/pack', description: '2-minute instant noodles.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Snacks', stock: 400, rating: 4.9, data_ai_hint: 'maggi noodles packet realistic', dealEndTime: tomorrow.toISOString(), badges: ['Limited Stock'] },
  { id: 'g21', name: 'Seviyan (Vermicelli)', price: 30, unit: '/200g', description: 'Roasted vermicelli for upma or kheer.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 150, rating: 4.5, data_ai_hint: 'vermicelli pasta heap' },
  { id: 'g22', name: 'Sooji (Semolina)', price: 40, unit: '/500g', description: 'Coarse semolina for upma and halwa.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 180, rating: 4.6, data_ai_hint: 'semolina flour in bowl' },
  { id: 'g23', name: 'Poha (Flattened Rice)', price: 35, unit: '/500g', description: 'Medium thickness poha.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 200, rating: 4.7, data_ai_hint: 'poha flattened rice' },
  { id: 'g24', name: 'Lijjat Papad', price: 50, unit: '/200g', description: 'Udad dal papad.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Snacks', stock: 130, rating: 4.8, data_ai_hint: 'lijjat papad packet' },
  { id: 'g25', name: 'Aam ka Achar (Mango Pickle)', price: 80, unit: '/400g', description: 'Spicy and tangy mango pickle.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Condiments', stock: 90, rating: 4.7, data_ai_hint: 'mango pickle jar' },
  { id: 'g26', name: 'Besan (Gram Flour)', price: 60, unit: '/500g', description: 'Fine gram flour.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Staples', stock: 140, rating: 4.6, data_ai_hint: 'besan gram flour' },
  { id: 'g27', name: 'Hing (Asafoetida)', price: 40, unit: '/50g', description: 'Strong and aromatic asafoetida.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Spices', stock: 100, rating: 4.8, data_ai_hint: 'asafoetida spice container' },
  { id: 'g28', name: 'Garam Masala', price: 50, unit: '/100g', description: 'Blend of whole spices.', image: 'https://placehold.co/600x600', category: 'grocery', subCategory: 'Spices', stock: 120, rating: 4.9, data_ai_hint: 'garam masala spices' }
];
